### ISSUE TITLE
Sobre valor da parcela invalida, devido a aplicação de desconto em um método anteriormente

### ISSUE THREAD

**Issue by hackin88** [elisei/moip-apenas-pagamento#3]
Bom dia

--

Sobre valor da parcela invalida, devido a aplicação de desconto em um método anteriormente selecionado

--

Gostaria de compartilhar a seguinte ocorrencia

--

A reprodução consiste nos seguintes passos

1.1

Criar uma promoção que aplica desconto a algum método de pagamento, pode ser no método "Cash On Delivery"

1.2

No checkout nativo, prosseguir e selecionar o método que tenha o desconto

Ao retornar selecione o método de Cartão de Crédito da MOIP

Veja que o valor da parcela está errada, sendo usado como base o valor com desconto relativo ao método anterior

1.3

Atualize a pagina

1.4

Em seguida selecione o método de Cartão de Crédito da MOIP

1.5

Veja que o valor da parcela está errada, sendo usado como base o valor com desconto relativo ao método anterior

-

**Comment by elisei** [comment]
Olá @hackin88 
Você se refere ao Moip ou de fato ao Pagseguro?

**Comment by hackin88** [comment]
Já corrigi o questionamento

**Comment by elisei** [comment]
Obrigado @hackin88 bom esse módulo não e para uso com checkout nativo, ele já tem um checkout próprio, por favor remova todos os arquivos que foram instalados com esse módulo e veja se com a versão adequado se problema persiste -> https://github.com/elisei/moip-apenas-pagamento/
