### ISSUE TITLE
O mês de expiração do cartão de crédito deve ser numérico

### ISSUE THREAD

**Issue by jessestain** [elisei/moip-apenas-pagamento#6]
bom dia Elisei, por favor esta acontecendo um erro na qual apresenta seguinte mensagem após colocar os dados do cartão de credito 

Encontramos alguns ao processar seu pedido. Por favor, entre em contato com nossa equipe. Erro: O mês de expiração do cartão de crédito deve ser numérico

não consegui arrumar

**Comment by elisei** [comment]
Oi @jessestain 
Isso geralmente ocorre por erro de js, vá na admin em Sistema > Configuração > Moip Avançado > e desabilite o uso de jquery do nosso módulo!

**Comment by jessestain** [comment]
@elisei Primeiramente quero agradecer pela rapidez por me ajudar. estou mandando um print das configurações que fiz. por favor queria ver se esta correto o que fiz pq o erro continua. 

Deus abençoe muito
![configuracao moip](https://user-images.githubusercontent.com/7496304/53435616-fa346380-39d7-11e9-9a94-5d27b4ea9872.jpg)
![js](https://user-images.githubusercontent.com/7496304/53435725-3798f100-39d8-11e9-946d-2a609a9435ea.jpg)

**Comment by elisei** [comment]
Oi @jessestain 

É de fato um problema de js, há 5 erros ali no console, tente fazer uma remoção condicional dos js conflitantes esse passo detalho aqui: https://github.com/elisei/moip-transparente-magento/wiki/3-Configurar-Checkout-Moip-Carrinho#2-conflito-de-js 
O modelo ai aplicado é para o nosso checkout mas você pode adaptar para o seu, se precisar de ajuda acione o suporte magento@moip.com.br com os dados de ftp e admin que ajudamos você por lá!

**Comment by jessestain** [comment]
Opa, muito obrigado vou tentar sim. Deus abençoe

**Comment by jessestain** [comment]
@elisei Muito Obrigado, deu certo.

Por gentileza, tem como acrescentar Widgets de Parcelamento, e Compra com 1 Clique no modulo moip apenas pagamento. 

desde já fico muito grato!
